### ISSUE TITLE
Implicit undeclared dependency on Dist::Zilla::Tester

### ISSUE THREAD

**Issue by kentfredric** [dagolden/Dist-Zilla-Plugin-CheckExtraTests#22]
This is not presently serious or likely to be serious with the staged changes to Test::DZil, however, the code in question appeared potentially problematic either way.

https://metacpan.org/source/DAGOLDEN/Dist-Zilla-Plugin-CheckExtraTests-0.026/t/checkxt.t#L29

`Dist::Zilla::Tester` is never explicitly loaded in this scope, and so DZil load order changes could conceivably break it.

t/withblib.t is similarly affected.

**Comment by kentfredric** [comment]
> This is not presently serious or likely to be serious with the staged changes 

Wow. I just worked out why this is: 

```
 $ find  | grep Test
./lib/Dist/Zilla/Plugin/RunExtraTests.pm
./lib/Dist/Zilla/Plugin/CheckExtraTests.pm
./t/lib/Test
./t/lib/Test/DZil.pm
```

**Comment by karenetheridge** [comment]
Tests still pass for me after locally patching Test::DZil.
