### ISSUE TITLE
RunExtraTests runs all files under xt/, including data files.

### ISSUE THREAD

**Issue by van-de-bugger** [dagolden/Dist-Zilla-Plugin-CheckExtraTests#26]
I have `xt/` directory, it contains few tests (with `.t` suffix) and few non-test, non-Perl non-scripts, but supporting data for tests. Namely, I have `perlcritic.ini` (a config file for `Test::Perl::Critic`) and `aspell.en.pws` (custom dictionary for `Test::PodSpelling`). `dzil test` and `dzil xtest` works as expected: the first command runs all the tests under `t/`, the second one runs all the tests under `xt/`. Adding `CheckExtraTests` to my `dist.ini` also works as expected: `dzil release` runs `t/` tests first (since I also use `TestRelease`), then runs `xt/` tests (and builds the distro twice; but it is documented).

Documentation recommends using `RunExtraTests` to avoid double build. Unfortunately, `RunExtraTests` does not work for me: `dzil test` runs *all the files* under `t/` and `xt/`, including non-Perl, non-`.t` files. Obviously, `xt/perlcritic.ini` and `xt/aspell.en.pws` fail. `dzil xtest` works as before, it runs only tests, `xt/*.t`, and ignores non-test files.

**Comment by dagolden** [comment]
@karenetheridge any idea what's going on with this?

**Comment by karenetheridge** [comment]
I'd want to see the output of each of these commands, and an `ls -lR` of the `t` and `xt` directories. It could be a Test::Harness or App::Prove problem, or something strange is up with the files themselves.

**Comment by van-de-bugger** [comment]
I can prepare a reproducer, but I do not see how to attach it to the issue. Any ideas how to pass you a file?

**Comment by dagolden** [comment]
I think the best thing is to paste them on gist.github.com and post the links here.

**Comment by dagolden** [comment]
Or upload a tarball to Dropbox and post that link.

**Comment by van-de-bugger** [comment]
Ok, thanks. I'll do it next time. Today I already updated the original post with small one-file reproducer. It does not require external files and can be easily copy-pasted from the post.

**Comment by karenetheridge** [comment]
I found the problem; will send a PR.
